name: Cloud Platform Deploy
description: Deploy to Cloud Platform using Helm

inputs:
  environment:
    description: The environment to deploy to (dev/staging/preprod/prod)
    required: true
  version:
    description: The version of the service to deploy
    required: true
  api:
    description: The KUBE_ENV_API
    required: true
  cert:
    description: The KUBE_CERT
    required: true
  cluster:
    description: The KUBE_CLUSTER
    required: true
  namespace:
    description: The KUBE_NAMESPACE
    required: true
  token:
    description: The KUBE_TOKEN
    required: true
  k8s_deployment_name:
    description: "Kubernetes deployment name"
    default: 'PROJECT_NAME'
    required: false
  changelog_git_paths:
    default: ""
    description: When set it will limit the file changes shown in the changelog to the specified paths only. Useful for multi-project builds.
    required: false
  show_changelog:
    description: Whether the changelog should be sent by slack
    required: false
  helm_additional_args:
    description: any additional helm arguments
    required: false
    default: ""
  helm_timeout:
    description: helm timeout period
    required: false
    default: 5m
  helm_dir:
    description: location of helm configuration
    required: false
    default: helm_deploy
  helm_allowlist_groups:
    description: values for location of allowlist groups file
    required: false
  helm_allowlist_version:
    description: setting for version of allowlist file
    required: false
  release_name:
    description: The name used for the Helm release
    required: false
    default: 'PROJECT_NAME'

outputs:
  deployment_changelog:
    description: "The changelog for the deployment"
    value: ${{ steps.version_history.outputs.deployment_changelog }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Authenticate
      uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/cloud-platform-auth@v2 # WORKFLOW_VERSION
      with:
        api: ${{ inputs.api }}
        cert: ${{ inputs.cert }}
        cluster: ${{ inputs.cluster }}
        namespace: ${{ inputs.namespace }}
        token: ${{ inputs.token }}

    - name: Get environment details
      shell: bash
      id: env
      run: |
        case ${{ inputs.environment }} in
          'development') environment='dev' ;;
          'preproduction') environment='preprod' ;;
          'production') environment='prod' ;;
          'staging') environment='staging' ;;
          *) environment=${{ inputs.environment }} ;;
        esac
        echo "environment=${environment}" | tee -a "$GITHUB_OUTPUT"

    - name: get version history
      uses: ministryofjustice/hmpps-github-actions/.github/actions/version_history@v2 # WORKFLOW VERSION
      if: ${{ inputs.show_changelog }}
      id: version_history
      with:
        app_version: ${{ inputs.version }}
        environment: ${{ inputs.environment }}
        namespace: ${{ inputs.namespace }}
        k8s_deployment_name: ${{ inputs.k8s_deployment_name }}
        changelog_git_paths: ${{ inputs.changelog_git_paths }}

    - name: Check for IP_ALLOWLIST_GROUPS_YAML
      shell: bash
      id: check-ip-allowlists
      run: |
        if [[ -n "${{ inputs.helm_allowlist_groups }}" ]]; then
          echo "${{ inputs.helm_allowlist_groups }}" | base64 --decode > ./ip-allowlist-groups.yaml
          echo "ALLOWLIST_GROUPS=--values ./ip-allowlist-groups.yaml" >> $GITHUB_OUTPUT
        fi

    - name: Check for IP_ALLOWLIST_GROUPS_VERSION
      shell: bash
      id: check-ip-allowlists-version
      run: |
        if [[ -n "${{ inputs.helm_allowlist_version }}" ]]; then
          echo "ALLOWLIST_VERSION=--set generic-service.allowlist_version=${{ inputs.helm_allowlist_version }}" >> $GITHUB_OUTPUT
        fi

    - name: Deploy
      shell: bash
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install helm yq

        # Update values file with PR tags
        yq -i '
          .generic-service.ingress.host = "pr-${{ github.event.pull_request.number }}." + .generic-service.ingress.host |
          .generic-service.image.tag = "pr-${{ github.event.pull_request.number }}" |
          .generic-service.nameOverride = "${{ inputs.release_name }}" |
          .generic-prometheus-alerts.targetApplication = "${{ inputs.release_name }}"
        ' "helm_deploy/values-${{ steps.env.outputs.environment }}.yaml"

        # Update Helm chart version
        yq -i ".appVersion = \"${{ inputs.version }}\"" \
          "${{ inputs.helm_dir }}/${{ github.event.repository.name }}/Chart.yaml"

        # Update Helm dependencies
        helm dependency update "${{ inputs.helm_dir }}/${{ github.event.repository.name }}"

        # Execute Helm upgrade
        exec helm upgrade '${{ inputs.release_name }}' \
                         '${{ inputs.helm_dir }}/${{ github.event.repository.name }}' \
          --atomic \
          --history-max 10 \
          --force \
          --install \
          --reset-values \
          --set 'version=${{ inputs.version }}' \
          --timeout ${{ inputs.helm_timeout }} \
          --values "helm_deploy/values-${{ steps.env.outputs.environment }}.yaml" \
          ${{ inputs.helm_additional_args }} \
          ${{ steps.check-ip-allowlists.outputs.ALLOWLIST_GROUPS }} \
          ${{ steps.check-ip-allowlists-version.outputs.ALLOWLIST_VERSION }} \
          --wait