services:
  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - "5432:5432"

  hmpps-auth:
    ports:
      - "9090:9090"

  coordinator-api:
    ports:
      - "8070:8080"

  arns-handover:
    ports:
      - "7070:7070"

  oasys-ui:
    image: quay.io/hmpps/hmpps-assess-risks-and-needs-oastub-ui:local
    build:
      target: development
    command: npm run start:dev
    ports:
      - "7072:3000"
      - "9230:9229"
    volumes:
      - ../assets:/app/assets
      - ../bin:/app/bin
      - ../esbuild:/app/esbuild
      - ../server:/app/server
      - ../test_results:/app/test_results
      - ../.eslintcache:/app/.eslintcache
      - ../.eslintignore:/app/.eslintignore
      - ../.eslintrc.json:/app/.eslintrc.json
      - ../.prettierrc:/app/.prettierrc
      - ../logger.ts:/app/logger.ts
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../server.ts:/app/server.ts
      - ../tsconfig.json:/app/tsconfig.json

  hmpps-auth-proxy:
    image: nginx:latest
    depends_on:
      - hmpps-auth
      - arns-handover
    networks:
      - hmpps
    ports:
      - "9091:9091"
      - "7071:7071"
    volumes:
      - ./hmpps-auth-proxy/nginx.conf:/etc/nginx/nginx.conf

  san-api:
    ports:
      - "8080:8080"
