services:
  oasys-ui:
    image: ghcr.io/ministryofjustice/hmpps-assess-risks-and-needs-oastub-ui:local
    build:
      target: development
    command: npm run start:dev
    ports:
      - "7072:3000"
      - "9230:9229"
    volumes:
      - ../assets:/app/assets
      - ../bin:/app/bin
      - ../esbuild:/app/esbuild
      - ../server:/app/server
      - ../test_results:/app/test_results
      - ../.eslintcache:/app/.eslintcache
      - ../.prettierrc:/app/.prettierrc
      - ../eslint.config.mjs:/app/eslint.config.mjs
      - ../logger.ts:/app/logger.ts
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../server.ts:/app/server.ts
      - ../tsconfig.json:/app/tsconfig.json
