---
# Per environment values which override defaults in hmpps-assess-risks-and-needs-oastub-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: arns-oastub-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://arns-oastub-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: 
