name: Build and Deploy PR (Ephemeral)
on:
  workflow_dispatch

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build docker image from hmpps-github-actions
    uses: ./.github/workflows/docker_build.yml
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push || true }}
      docker_multiplatform: false
#  deploy_dev:
#    name: Deploy to the development environment
#    needs:
#      - build
#      - helm_lint
#    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
#    secrets: inherit
#    with:
#      environment: 'dev'
#      app_version: '${{ needs.build.outputs.app_version }}'
