name: Build & push docker image and deploy to environment

on:
  workflow_call:
    inputs:
      docker_registry:
        description: Docker registry
        required: true
        type: string
      registry_org:
        description: Docker registry organisation
        required: true
        type: string
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable tags
        required: false
        type: string
      additional_docker_build_args:
        description: Additional docker build arguments
        required: false
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        type: boolean
      tag_latest:
        description: Tag image as 'latest'
        type: boolean
        required: false
        default: true
      docker_multiplatform:
        description: Docker image build multiplatform or not
        required: true
        type: boolean
        default: true

    secrets:
      HMPPS_QUAYIO_USER:
        required: false
      HMPPS_QUAYIO_TOKEN:
        required: false

    outputs:
      app_version:
        description: The version of the app as generated by create_app_version
        value: ${{ jobs.docker_build.outputs.version }}

permissions:
  contents: read
  packages: write

jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.app_version.outputs.version }}
    steps:
      - id: app_version
        name: Application Version Creator
        uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/create_app_version@v2 # WORKFLOW_VERSION

      - name: Define Image Tags
        id: define_tags
        run: |
          echo "IMAGE_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
          echo "PUSH_IMAGE=true" >> $GITHUB_ENV

      - name: Build docker
        uses: ./.github/actions/build-docker
        with:
          repository_name: ${{ github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          push: ${{ env.PUSH_IMAGE }}
          app_version: ${{ env.IMAGE_TAG }}
          additional_docker_build_args: ${{ inputs.additional_docker_build_args }}
          tag_latest: ${{ inputs.tag_latest }}