name: Run end-to-end tests

on:
  workflow_call:
    inputs:
      app_version:
        description: App version
        required: true
        type: string

permissions:
  contents: read

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: build_image
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/build_image.tar

      - name: Set APP_VERSION
        run: |
          export APP_VERSION=${{ inputs.app_version }}
          echo $APP_VERSION

      - name: Stand up a test environment
        run: make test-up

      - name: Run the end-to-end tests
        run: make e2e-ci

      - name: Export container logs
        if: failure()
        run: make save-logs OUTPUT_LOGS_DIR=${{ runner.temp }}/docker-logs PROJECT_NAME="hmpps-assess-risks-and-needs-test"

      - name: Upload test results
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: test_results
          path: |
            test_results
            cypress/videos
            cypress/screenshots
            ${{ runner.temp }}/docker-logs
