name: Build and test PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node_build:
    name: Build
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_build.yml@upload-image-to-artifacts
    secrets: inherit

  node_unit_tests:
    name: Unit tests
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/node_unit_tests.yml@upload-image-to-artifacts
    needs: [node_build]
    secrets: inherit

  helm_lint:
    name: Helm lint
    strategy:
      matrix:
        environments: ['dev', 'test']
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@upload-image-to-artifacts
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}

  build_docker:
    name: Build docker image
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@upload-image-to-artifacts
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      tag_latest: false
      push: false
      load: true
      docker_multiplatform: false
      upload_image_artifact: true
      image_artifact_retention_days: 2

#  e2e_test:
#    needs: [build_docker]
#    uses: ./.github/workflows/e2e_test.yml
#    with:
#      app_version: ${{ needs.build_docker.outputs.app_version }}

  publish_docker:
    name: Publish docker image
    needs:
      - node_build
      - node_unit_tests
      - build_docker
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_push.yml@upload-image-to-artifacts
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      app_version: ${{ needs.build_docker.outputs.app_version }}
      tag_latest: true

  deploy_dev:
    name: Deploy to the development environment
    needs:
      - build_docker
      - publish_docker
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@upload-image-to-artifacts
    secrets: inherit
    with:
      environment: 'dev'
      app_version: '${{ needs.build_docker.outputs.app_version }}'
